### ISSUE TITLE
Malformed css property

### ISSUE THREAD

**Issue by freitasskeeled** [asika32764/vue-animate.css#21]
Hi,

I noticed a bug with the "make-transitions" mixin. The property `animation-name` is created with quotes and that is invalid css.

Here is a short gif showing the problem: [GIF](https://gph.is/2nEzAq0)

To fix it, I simply removed the single quotes from the 4 `animation-name` property definitions.

Best regards,

Rui Freitas

**Comment by asika32764** [comment]
Seem's the main subject of https://github.com/asika32764/vue2-animate/pull/20 to solved.

**Comment by freitasskeeled** [comment]
Hi,

I didn't notice the PR. I search for issues but not PR (my bad).

Do you an estimation to when that PR is going to be merged?

Best regards,

Rui Freitas

**Comment by asika32764** [comment]
The PR author says he will do some update but I didn't see new commits, I will merge it maybe this weekend.

**Comment by asika32764** [comment]
2.1.0 has released
https://github.com/asika32764/vue2-animate/releases/tag/2.1.0
