### ISSUE TITLE
How to use a different animation for enter and leave?

### ISSUE THREAD

**Issue by joelataylor** [asika32764/vue-animate.css#23]
Quick question, how do you apply a different animation for enter and leave?

I'd like to `fadeDown` on enter and `fadeUp` for leave.

```
<transition name="fadeDown">
  <div> content here </div>
</transition>
```

**Comment by asika32764** [comment]
Try

```html
<transition enter-active-class="fadeDown" leave-active-class="fadeUp">
```

**Comment by joelataylor** [comment]
@asika32764 - yep! that worked. I'm assuming this is just using the core `animate.css` package with default vue.js transitions and not your plugin?

**Comment by asika32764** [comment]
This package was written by https://github.com/haydenbbickerton and I rewrote it for Vuejs2.0

Some animate.css classes changed to make it suitable for Vue transitions so that we don't need to manually write enter and leave classes.

**Comment by asika32764** [comment]
Close as issue resolved.
