### ISSUE TITLE
与ui框架内置的动画产生冲突，建议name能添加命名空间

### ISSUE THREAD

**Issue by 313224646** [asika32764/vue-animate.css#24]
我很喜欢使用vue2-animate，但它设置的过渡名称(name)实在太容易与其他模块产生冲突了，例如我使用的vant-ui框架里面的Toast提示，导致Toast提示弹出的时候产生强烈的抖动。由此，我建议name可以使用命名空间。

**Comment by asika32764** [comment]
We can add a prefix variable to add namespace to classes, but this needs developer to build vue2-animate themselves.
