### ISSUE TITLE
Adjust to animation changes in Vue@2.1.8

### ISSUE THREAD

**Issue by karol-f** [asika32764/vue-animate.css#3]
Changes are described here - https://github.com/vuejs/vue/releases/tag/v2.1.8

**Comment by asika32764** [comment]
Hi, It's seems 2.1.8 is a simple revert of animation.

Is there any B/C break about `vue2-animate.css`?

This package working well with vue after 2.1.10, see: http://about.asika.tw/vue2-animate/

**Comment by karol-f** [comment]
@asika32764 From changelog:

> In order to properly solve #4510, a new type of transition class (-to) is introduced.

and 

> Both v-leave and v-leave-active behave exactly like before. The only difference between v-leave-to and v-leave-active is that **it is applied one frame after the transition starts.**

So basically the problem is in e.g. vue-router transitions, when briefly, in the first frame, object that is transitioning is not styled.

Maybe I did sth wrong but it seemed like Vue update (with added `-to` classes) break a little existing transitions.

**Comment by asika32764** [comment]
Sorry I'm too busy to research about this issue, feel free to create a PR if you can make sure what should be change.
