### ISSUE TITLE
How do I set up duration of the animation????

### ISSUE THREAD

**Issue by andrisole92** [asika32764/vue-animate.css#9]
Any help please

**Comment by asika32764** [comment]
This is css file so the duration is hard code in style.

You can change duration here and re-compile LESS file for yours.
https://github.com/asika32764/vue2-animate/blob/master/src/vue2-animate.less#L10

**Comment by andrisole92** [comment]
I need fade to be fast in one place and slow in another. Can I achieve that? It seems like no

**Comment by asika32764** [comment]
Just modify css directly
https://github.com/asika32764/vue2-animate/blob/master/dist/vue2-animate.css#L452

If you want to use different duration to same effect, you can only copy and rename it.

**Comment by asika32764** [comment]
Another way is to use jQuery to do animation you want, remember to wrap it by a component or directive.

The DOM animation is jQuery's job not Vue's.

**Comment by DaxChen** [comment]
I just added 

```css
.foo {
  animation-duration: 0.3s
}
```

to override the style and it works!

example:

```html
<transition name="fade">
  <p v-if="show" style="animation-duration: 0.3s">hello</p>
</transition>
```
